GET http://localhost:3000/api/car

###

POST http://localhost:3000/api/car
Content-Type: application/json

{
    "name": "Ferrari",
    "mount": 7
}

###

GET http://localhost:3000/api/house

###


POST http://localhost:3000/api/house
Content-Type: application/json

{
    "location": "Bandung",
    "name": "griya alam",
    "price": 1000000
}

###
GET http://localhost:3000/api/user

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "Bangkit Juang Raharjo",
    "username": "Juang",
    "email": "juangraharjo03@gmail.com",
    "password": "juang123",
    "phone": "08123456789"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "juangraharjo007@gmail.com",
    "password": "juang123"
}

###
GET http://localhost:3000/api/car
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Imp1YW5ncmFoYXJqbzAwN0BnbWFpbC5jb20iLCJwYXNzd29yZCI6IiRhcmdvbjJpZCR2PTE5JG09NjU1MzYsdD0zLHA9NCQ3L0NWSHpxWWRxUHB1dklaaFZhbTBRJG1XazBsSjFVRytiTitpZ2lWV3pyZjd4L3AycU5reXlUb3dTc0lwZ05MZm8iLCJpYXQiOjE2NzE2MzU1MzksImV4cCI6MTY3MjI0MDMzOX0.V3kxQmoTY5pf9R10QGj2YsURKtZftrMHW4x5-ZD6SRw