GET http://localhost:3000/api/car

###

POST http://localhost:3000/api/car
Content-Type: application/json

{
    "name": "Ferrari",
    "mount": 7
}

###

GET http://localhost:3000/api/house

###


POST http://localhost:3000/api/house
Content-Type: application/json

{
    "location": "Bandung",
    "name": "griya alam",
    "price": 1000000
}

###
GET http://localhost:3000/api/user

###

POST http://localhost:3000/api/register
Content-Type: application/json

{
    "name": "Bangkit Juang Raharjo",
    "username": "Juang",
    "email": "juangraharjo03@gmail.com",
    "password": "juang123",
    "phone": "08123456789"
}

###

POST http://localhost:3000/api/login
Content-Type: application/json

{
    "email": "juangraharjo007@gmail.com",
    "password": "juang123"
}

###
GET http://localhost:3000/api/car
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqdWFuZ3JhaGFyam8wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkNy9DVkh6cVlkcVBwdXZJWmhWYW0wUSRtV2swbEoxVUcrYk4raWdpVld6cmY3eC9wMnFOa3l5VG93U3NJcGdOTGZvIiwiaWF0IjoxNjcxOTU4OTYzLCJleHAiOjE2NzI1NjM3NjN9.GSRci1IbxrfPjaDfWXMT-tkPVBidVv54fxm2ka9R_74

###
POST http://localhost:3000/api/car
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqdWFuZ3JhaGFyam8wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkNy9DVkh6cVlkcVBwdXZJWmhWYW0wUSRtV2swbEoxVUcrYk4raWdpVld6cmY3eC9wMnFOa3l5VG93U3NJcGdOTGZvIiwiaWF0IjoxNjcxOTU4OTYzLCJleHAiOjE2NzI1NjM3NjN9.GSRci1IbxrfPjaDfWXMT-tkPVBidVv54fxm2ka9R_74
Content-Type: application/json

{
    "name": "lamborgini",
    "mount": 10
}

###
GET http://localhost:3000/api/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqdWFuZ3JhaGFyam8wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkNy9DVkh6cVlkcVBwdXZJWmhWYW0wUSRtV2swbEoxVUcrYk4raWdpVld6cmY3eC9wMnFOa3l5VG93U3NJcGdOTGZvIiwiaWF0IjoxNjcxOTc4NTYxLCJleHAiOjE2NzI1ODMzNjF9.2DNBgZE_BOSFGnP7vBs8KZCLhq19vRao-HimK1DUTts

###
GET http://localhost:3000/api/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqdWFuZ3JhaGFyam8wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkNy9DVkh6cVlkcVBwdXZJWmhWYW0wUSRtV2swbEoxVUcrYk4raWdpVld6cmY3eC9wMnFOa3l5VG93U3NJcGdOTGZvIiwiaWF0IjoxNjcxOTc4NTYxLCJleHAiOjE2NzI1ODMzNjF9.2DNBgZE_BOSFGnP7vBs8KZCLhq19vRao-HimK1DUTts

###
POST http://localhost:3000/api/book
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJqdWFuZ3JhaGFyam8wMDdAZ21haWwuY29tIiwicGFzc3dvcmQiOiIkYXJnb24yaWQkdj0xOSRtPTY1NTM2LHQ9MyxwPTQkNy9DVkh6cVlkcVBwdXZJWmhWYW0wUSRtV2swbEoxVUcrYk4raWdpVld6cmY3eC9wMnFOa3l5VG93U3NJcGdOTGZvIiwiaWF0IjoxNjcxOTc4NTYxLCJleHAiOjE2NzI1ODMzNjF9.2DNBgZE_BOSFGnP7vBs8KZCLhq19vRao-HimK1DUTts
Content-Type: application/json

{
    "name": "Oaken Shield",
    "amount": 10
}